baseURL = "https://ivanasteven.com/"
languageCode = "en-us"
title = "Ivana & Steven | Wedding Photography & Filmmaker"
theme = "hugo-hero-theme"

[params]
  google_analytics_id="UA-99821839-1"
  google_optimize_id="GTM-KDKZNDT"

  sitewide_message="Want to work with us? Contact us now!"
  sitewide_url="https://ivanasteven.com/contact"

  [params.homepage_meta_tags]
    meta_description = "Ivana & Steven are a husband and wife photography & filmmaker duo. We are based in Chicago but travel worldwide."
    meta_og_title = "Ivana & Steven | Photographer & Filmmaker"
    meta_og_type = "website"
    meta_og_url = "https://ivanasteven.com/"
    meta_og_image = "/"
    meta_og_description = "Ivana & Steven are a husband and wife photography & filmmaker duo. We are based in Chicago but travel worldwide."

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

[[menu.main]]
    name = "Journal"
    url = "/journal/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"