baseURL = "https://ivanasteven.com/"
languageCode = "en-us"
title = "Ivana & Steven"
theme = "hugo-hero-theme"

[params]
  google_analytics_id="UA-99821839-1"

  [params.homepage_meta_tags]
    meta_description = "Ivana and Steven are a husband &amp; wife photographer duo. We are natural light Chicago and destination wedding &amp; family photographers."
    meta_og_title = "Ivana &amp; Steven Photography"
    meta_og_type = "website"
    meta_og_url = "https://ivanasteven.com/"
    meta_og_image = "/"
    meta_og_description = "Ivana and Steven are a husband &amp; wife photographer duo. We are natural light Chicago and destination wedding &amp; family photographers."

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

[[menu.main]]
    name = "Journal"
    url = "/journal/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"