backend:
  name: git-gateway

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "portfolio"
    label: "Wedding Photography"
    folder: "content/portfolio/weddings/photos"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Wedding Films"
    folder: "content/portfolio/weddings/films"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Family Session"
    folder: "content/portfolio/families"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Header Position", name: "headerPosition", widget: "list", default: ["topFull"]}      
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "General Events"
    folder: "content/portfolio/events"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Thumbnail Percent", name: "thumbnailPercent", widget: "list", default: ["10% 20%"]}
      - {label: "Hero Position Percent", name: "heroPositionPercent", widget: "list", default: ["10% 20% !important"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portraits"
    folder: "content/portfolio/portraits"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "journal"
    label: "Journal"
    folder: "content/journal"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "reviews"
    label: "Reviews"
    folder: "content/reviews"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "slider"
    label: "Homepage Slider"
    folder: "content/slider"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "travel"
    label: "Travel"
    folder: "content/travel"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Heading", name: "heroHeading", widget: "string"}
      - {label: "Hero Subheading", name: "heroSubHeading", widget: "string"}
      - {label: "Hero Background Image", name: "heroBackground", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Main Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Hero Slider", name: slider, widget: list, fields: [
              {label: "Image", name: "image", widget: image},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro Blurb", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"},
              {label: "Link", name: "link", widget: "string"}]}
          - {label: "Additional Sections", name: additional_section, widget: list, fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text