---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/pages/about
  label: About Us Page
  create: all
  match: "**/*"
- type: directory
  path: content/pages
  label: Custom Pages
  create: all
  match: "**/*"
  exclude: about/*
- type: document
  path: content/homepage/about.md
  label: Homepage - About Us
- type: directory
  path: content/portfolio/portraits
  label: Portrait Session
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio/events
  label: Events Session
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio/weddings
  label: Wedding Session
  create: all
  match: "**/*"
- type: directory
  path: content/portfolio/families
  label: Family Session
  create: all
  match: "**/*"
- type: directory
  path: content/journal
  label: Journal
  create: all
  match: "**/*"
- type: directory
  path: content/reviews
  label: Reviews
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/slider
  label: Slider
  create: all
  match: "**/*"
- type: directory
  path: content/404
  label: '404'
  create: all
  match: "**/*"
- type: directory
  path: content/travel
  label: Travel
  create: all
  match: "**/*"
upload_dir: static/image/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.59.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.59.1
